services:
  scrape:
    image: scrape:1.0
    volumes:
      - ./scrape:/scrape
      - ./secrets:/secrets
  preprocess:

    image: amidgley/preprocess:3.0_linux

    volumes:
      - ./preprocess:/preprocess
      - ./secrets:/secrets
  train:
    image: amidgley/train:linux_2.0
    volumes:
      - ./train:/train
      - ./secrets:/secrets