version: '3.7'
services:
  scrape:
    image: scrape:1.0
    volumes:
      - ./scrape:/scrape
      - ./secrets:/secrets
  preprocess:
    image: amidgley/preprocess:3.0
    volumes:
      - ./preprocess:/preprocess
      - ./secrets:/secrets